// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micro/go-api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type UserInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*UserInfo)(nil), "UserInfo")
	proto.RegisterType((*Token)(nil), "Token")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x77, 0xab, 0x5d, 0xbb, 0x23, 0xa8, 0x04, 0x0f, 0xa5, 0x27, 0xc9, 0x45, 0x0f, 0x9a,
	0x82, 0xfb, 0x1b, 0x44, 0x04, 0x4f, 0x45, 0xc1, 0x6b, 0x76, 0x3b, 0xd6, 0x41, 0x9b, 0x89, 0x49,
	0xaa, 0xf8, 0xef, 0x25, 0x89, 0x5b, 0x6f, 0xf9, 0xbe, 0x17, 0x1e, 0xf3, 0x00, 0x26, 0x8f, 0x4e,
	0x59, 0xc7, 0x81, 0x9b, 0xcb, 0x81, 0xc2, 0xdb, 0xb4, 0x55, 0x3b, 0x1e, 0xdb, 0x91, 0x76, 0x8e,
	0xdb, 0x81, 0x6f, 0xb4, 0xa5, 0x36, 0xc5, 0xad, 0xb6, 0x94, 0x3f, 0xca, 0x23, 0x28, 0xef, 0x46,
	0x1b, 0x7e, 0x64, 0x07, 0xd5, 0xb3, 0x47, 0xf7, 0x60, 0x5e, 0x59, 0x9c, 0x40, 0x41, 0x7d, 0xbd,
	0xbc, 0x58, 0x5e, 0xad, 0xbb, 0x82, 0x7a, 0xd1, 0x40, 0x15, 0xbb, 0x8d, 0x1e, 0xb1, 0x2e, 0x92,
	0x9d, 0x39, 0x66, 0x56, 0x7b, 0xff, 0xcd, 0xae, 0xaf, 0x0f, 0x72, 0xb6, 0x67, 0xb9, 0x81, 0xf2,
	0x89, 0xdf, 0xd1, 0x88, 0x73, 0x28, 0x43, 0x7c, 0xfc, 0x75, 0x66, 0x88, 0xf6, 0x4b, 0x7f, 0x50,
	0x9f, 0x3a, 0xab, 0x2e, 0xc3, 0xed, 0x0b, 0x1c, 0xc6, 0x43, 0xc4, 0x35, 0x94, 0x8f, 0x3c, 0x90,
	0x11, 0xa7, 0x6a, 0x60, 0x15, 0x2f, 0xee, 0xf0, 0x73, 0x42, 0x1f, 0x9a, 0xb3, 0x7f, 0xe1, 0x2d,
	0x1b, 0x8f, 0x72, 0x21, 0x24, 0x1c, 0xdf, 0x63, 0x98, 0x17, 0xac, 0x54, 0x5a, 0xd5, 0xac, 0xd5,
	0x5e, 0xc9, 0xc5, 0x76, 0x95, 0x26, 0x6f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x27, 0xf0,
	0x84, 0x29, 0x01, 0x00, 0x00,
}
